china:
 Shanghai:
  - Baoshan district
  - Changning district
  - Chongming island
  - Hongkou district
  - Huangpu district 
  - Fengxian district
  - Jiading district
  - Jingan district
  - Jinshan district
  - Luwan district
  - Minhang district
  - Nanhui district
  - Pudong new area
  - Putuo district
  - Qingpu district
  - Xuhui district
  - Yangpu district
  - Zhabei district
 Beijing:
  - Changping district
  - Chaoyang district
  - Chongwen district
  - Dongcheng district
  - Fangshan district
  - Fengtai district
  - Haidian district
  - Huairou district
  - Mentougou district
  - Miyun district
  - Pinggu district
  - Shijingshan district
  - Shunyi district
  - Tongzhou district
  - Xicheng district
  - Xuanwu district
  - Yanqing district 
 Hong Kong:
  - Central and western district
  - Eastern area
  - Dapu  district
  - Guantang  district
  - Huangdaxian district
  - Jiulong district
  - Kuiqing district
  - Lidao district
  - Northern district
  - Quanwan  district
  - Shatian district
  - Shenshuibu  district
  - Southern area
  - Tunmen district
  - Wanzai district
  - Xigong district
  - Yuanlang district
  - Youjianwang district 
 Guangzhou:
  - Baiyun district
  - Conghua district
  - Fanyu district
  - Haizhu district
  - Huadu district
  - Huangpu district
  - Liwan district
  - Luogang district
  - Nansha district
  - Tianhe district
  - Yuexiu district
  - Zengcheng district
 Changsha:
  -
 Changchun:
  -
 Chengdu:
  -
 Chongqing:
  -
 Dalian:
  -
 Fuzhou:
  -
 Haerbin:
  -
 Hangzhou:
  -
 Nanchang:
  -
 Nanjing:
  -
 Jinan:
  -
 Qingdao:
  -
 Shenyang:
  -
 Shenzhen:
  -
 Shijiazhuang:
  -
 Suzhou:
  -
 Tianjin:
  -
 Wenzhou:
  -
 Wuhan:
  -
 Wuxi:
  -
 Xiamen:
  -
 Xi’an:
  -
 Yantai:
  -
 Zhengzhou:
  -