## YAML Template.
development:
  sandbox: true
  username: mahesh.bhise-facilitator_api1.hotmail.com
  password: 1387361633
  signature: An5ns1Kso7MWUdW4ErQKJJJ4qi4-AM9eNf.DHkttiQzI08UTwag3Xwxg

production:
  sandbox: true
  username: mahesh.bhise-facilitator_api1.hotmail.com
  password: 1387361633
  signature: An5ns1Kso7MWUdW4ErQKJJJ4qi4-AM9eNf.DHkttiQzI08UTwag3Xwxg

test:
  sandbox: false
  username: maheddasdash.bhise-facilitator_api1.hotmail.com
  password: 1387361323633
  signature: An5ns1Kso7sadadaMWUdW4ErQKJJJ4qi4-AM9eNf.DHkttiQzI08UTwag3Xwxg
